dist: trusty
language: node_js
node_js:
  - "node"
  - "lts/*"
  
cache:
  directories:
    - node_modules

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test:ci
  - npm run build

after_script:
  - ./cc-test-reporter after-build --coverage-input-type lcov --debug --exit-code $TRAVIS_TEST_RESULT

on:
  branch: master
